server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/MovieAppDB
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
